import { motion } from 'framer-motion'
import { useState } from 'react'
import type { IconItem, SiteData } from '../types'
import { icons } from '../utils/icons'
import { SectionHeading } from './SectionHeading'
const rise = { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: .2 }, transition: { duration: .55 } }
function Icon({ name }: { name: string }) { const C = icons[name] ?? icons.Network; return <C aria-hidden="true" /> }
export function Hero({ data, ambient }: { data: SiteData['hero']; ambient: SiteData['ambient'] }) { return <section className="hero" id={data.id}><div className="orb orb-one"/><div className="orb orb-two"/><div className="signal-field" aria-hidden="true"><div className="orbit orbit-a"/><div className="orbit orbit-b"/>{ambient.nodes.map((node, index) => <div className={`signal-node node-${index + 1}`} key={node.label}><i/><span>{node.label}<small>{node.detail}</small></span></div>)}</div><motion.div {...rise} className="container hero-inner"><p className="eyebrow">{data.eyebrow}</p><h1>{data.headline} <em>{data.highlight}</em></h1><p className="hero-copy">{data.description}</p><div className="actions"><a className="button" href={data.primaryCta.href}>{data.primaryCta.label}<Icon name="ArrowUpRight"/></a><a className="text-link" href={data.secondaryCta.href}>{data.secondaryCta.label}<Icon name="ArrowUpRight"/></a></div><div className="proof">{data.proof.map(item => <span key={item}><i>✦</i>{item}</span>)}</div></motion.div></section> }
export function Intro({ data }: { data: SiteData['intro'] }) { return <section id={data.id} className="section"><motion.div {...rise} className="container split intro"><SectionHeading {...data}/><div className="statement"><strong>{data.metric}</strong><p>{data.metricLabel}</p></div></motion.div></section> }
function Card({ item, index }: { item: IconItem; index: number }) { return <motion.article {...rise} transition={{ duration: .5, delay: index * .08 }} className="card"><div className="card-icon"><Icon name={item.icon}/></div>{item.eyebrow && <p className="card-number">{item.eyebrow}</p>}{item.label && <p className="card-stage">{item.label}</p>}<h3>{item.title}</h3><p>{item.description}</p>{item.tags && <div className="tags">{item.tags.map(tag => <span key={tag}>{tag}</span>)}</div>}</motion.article> }
export function CardGrid({ data }: { data: SiteData['services'] | SiteData['traffic'] | SiteData['partners'] }) { return <section className="section section-tint" id={data.id}><div className="container"><SectionHeading {...data}/><div className={`card-grid grid-${data.items.length}`}>{data.items.map((item, i) => <Card item={item} index={i} key={item.title}/>)}</div></div></section> }
export function TabbedTraffic({ data }: { data: SiteData['trafficPrograms'] }) { const [active, setActive] = useState(0); const tab = data.tabs[active]; return <section className="section traffic-programs" id={data.id}><div className="container"><SectionHeading {...data}/><div className="traffic-tabs" role="tablist">{data.tabs.map((item, index) => <button key={item.label} role="tab" aria-selected={active === index} className={active === index ? 'active' : ''} onClick={() => setActive(index)}><small>{item.number}</small>{item.label}</button>)}</div><motion.div key={tab.label} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="traffic-stage"><div className="traffic-intro"><span>{tab.number}</span><h3>{tab.title}</h3><p>{tab.description}</p></div><div className="traffic-tiles">{tab.tiles.map((item, index) => <article key={item.title}><div className="tile-top"><Icon name={item.icon}/><b>0{index + 1}</b></div><h4>{item.title}</h4><p>{item.description}</p></article>)}</div></motion.div></div></section> }
export function TrafficScale({ data }: { data: SiteData['trafficScale'] }) { return <section id={data.id} className="section scale-section"><div className="container"><SectionHeading {...data}/><div className="scale-steps">{data.items.map((item, index) => <motion.article {...rise} transition={{ duration: .5, delay: index * .1 }} key={item.title}><div className="scale-number">{item.eyebrow}</div><div className="scale-icon"><Icon name={item.icon}/></div><h3>{item.title}</h3><p>{item.description}</p></motion.article>)}</div></div></section> }
export function Industries({ data }: { data: SiteData['industries'] }) { return <section id={data.id} className="section"><motion.div {...rise} className="container split industries"><SectionHeading {...data}/><div className="industry-list">{data.items.map((item, i) => <div key={item}><span>0{i + 1}</span>{item}</div>)}</div></motion.div></section> }
export function Technology({ data }: { data: SiteData['technology'] }) { return <section id={data.id} className="section"><motion.div {...rise} className="container tech-panel"><div><SectionHeading {...data}/><a href={data.cta.href} className="button">{data.cta.label}<Icon name="ArrowUpRight"/></a></div><ul>{data.points.map(point => <li key={point}><Icon name="Check"/>{point}</li>)}</ul></motion.div></section> }
export function Testimonials({ data }: { data: SiteData['testimonials'] }) { return <section id={data.id} className="section"><div className="container"><SectionHeading {...data}/><div className="testimonials">{data.items.map((item, i) => <motion.figure {...rise} transition={{ duration: .5, delay: i * .1 }} key={item.quote}><blockquote>“{item.quote}”</blockquote><figcaption><b>{item.name}</b><span>{item.role}</span></figcaption></motion.figure>)}</div></div></section> }
export function Insights({ data }: { data: SiteData['insights'] }) { return <section id={data.id} className="section section-tint"><div className="container"><SectionHeading {...data}/><div className="insights"><motion.article {...rise} className="featured-insight"><p>{data.featured.tag}</p><h3>{data.featured.title}</h3><span>{data.featured.description}</span><a className="text-link" href={data.featured.cta.href}>{data.featured.cta.label}<Icon name="ArrowUpRight"/></a></motion.article><div className="insight-list">{data.items.map((item, index) => <motion.article {...rise} transition={{ duration: .5, delay: index * .1 }} key={item.title}><p>{item.tag}</p><h3>{item.title}</h3><span>{item.description}</span></motion.article>)}</div></div></div></section> }
export function Accordion({ data }: { data: SiteData['faqs'] }) { const [open, setOpen] = useState(0); return <section id={data.id} className="section"><div className="container faq"><SectionHeading {...data}/><div className="accordion">{data.items.map((item, index) => <article className={open === index ? 'open' : ''} key={item.title}><button onClick={() => setOpen(open === index ? -1 : index)} aria-expanded={open === index}><span>0{index + 1}</span>{item.title}<b>{open === index ? '−' : '+'}</b></button>{open === index && <motion.p initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}>{item.description}</motion.p>}</article>)}</div></div></section> }
export function Contact({ data }: { data: SiteData['contact'] }) { const fields = Object.entries(data.form.labels); return <section id={data.id} className="section"><div className="container contact"><div><SectionHeading {...data}/><a className="email" href={`mailto:${data.email}`}>{data.email}</a><div className="contact-points">{data.items.map(item => <div key={item.title}><b>{item.title}</b><span>{item.detail}</span></div>)}</div></div><form onSubmit={e => e.preventDefault()}>{fields.map(([key, label]) => <label key={key}>{label}{key === 'message' ? <textarea name={key} rows={4}/> : <input name={key} type={key === 'email' ? 'email' : 'text'}/>}</label>)}<button className="button" type="submit">{data.form.button}<Icon name="ArrowUpRight"/></button></form></div></section> }
